name: Playwright Tests

on:
  push:
    branches:
      - main # Auto run on push to branch main
  workflow_dispatch: # Manual execution from GitHub Actions web UI

jobs:
  build-and-test:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: dotnet build --configuration Release --no-restore

      - name: Install browsers
        run: pwsh .\Automation\bin\Release\net8.0\playwright.ps1 install --with-deps chromium # If no specific browser is passed as the last parameter, all browsers are installed
                
      - name: Run Playwright tests
        run: dotnet test --settings .\Automation\Configuration\RunSettings\demo-chromium.runsettings

      - name: Generate report
        run: dotnet run --project .\Reporting\Reporting.csproj -- "C:\TestResults\test.xml"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: C:\TestResults
